version: '2'

services:
    caddy:
        container_name: caddy
        image: florentindubois/infrastructure:caddy

        links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - h5ai
            - rainloop

        volumes:
            - /srv/caddy:/root/.caddy

        depends_on:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - h5ai

        ports:
            - "443:2015"
            - "80:2015"
