version: '2'

services:
    caddy:
        container_name: caddy
        image: florentindubois/infrastructure

        external_links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge

        ports:
            - "80:2015"
            - "443:2015"
