version: '2'

services:
    caddy:
        container_name: caddy
        image: florentindubois/infrastructure:caddy

        external_links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - h5ai
            - rainloop

        volumes:
            - /srv/caddy:/root/.caddy

        ports:
            - "443:443"
            - "80:80"
