version: '2'

services:
    couchpotato:
        container_name: couchpotato
        image: linuxserver/couchpotato

        environment:
            - PGID=0
            - PUID=0

        volumes:
            - /srv/couchpotato/config:/config
            - /srv/couchpotato/downloads:/downloads
            - /srv/couchpotato/movies:/movies
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "5050"
