version: '2'

services:
    deluge:
        container_name: deluge
        image: linuxserver/deluge

        environment:
            - PUID=0
            - PGID=0

        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "8112"
