version: '2'

services:
    portfolio:
        container_name: portfolio
        image: florentindubois/portfolio:latest
        restart: always

        environment:
            - NODE_ENV=production

        expose:
            - "80"

    mariadb:
        container_name: mariadb
        image: mariadb:latest
        restart: always

        environment:
            - MYSQL_ROOT_PASSWORD=

        expose:
            - "3306"

        volumes:
            - /srv/mariadb:/var/lib/mysql

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always

        expose:
            - "27017"

        volumes:
            - /srv/mongodb:/data/db

    kraken:
        container_name: kraken
        image: florentindubois/kraken:stable
        restart: always

        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
            - MONGODB_BASE=kraken
            - NODE_ENV=production

        volumes:
            - /srv:/usr/src/app/mount

        expose:
            - "80"

        links:
            - mongodb

        depends_on:
            - mongodb

    owncloud:
        container_name: owncloud
        image: owncloud:latest
        restart: always

        expose:
            - "80"

        volumes:
            - /srv/owncloud:/var/www/html

        links:
            - mariadb

        depends_on:
            - mariadb

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: always

        environment:
            - PUID=0
            - PGID=0

        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "8112"
            - "58846"

        ports:
            - "7000-7009:7000-7009"

    sickrage:
        container_name: sickrage
        image: binhex/arch-sickrage:latest
        restart: always

        expose:
            - "8081"

        volumes:
            - /srv/sickrage/media:/media
            - /srv/sickrage/data:/data
            - /srv/sickrage/config:/config
            - /etc/localtime:/etc/localtime:ro

        environment:
            - PUID=0
            - GUID=0

        links:
            - deluge

        depends_on:
            - deluge

    couchpotato:
        container_name: couchpotato
        image: linuxserver/couchpotato:latest
        restart: always

        environment:
            - PGID=0
            - PUID=0

        volumes:
            - /srv/couchpotato/config:/config
            - /srv/couchpotato/downloads:/downloads
            - /srv/couchpotato/movies:/movies
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "5050"

        links:
            - deluge

        depends_on:
            - deluge

    rainloop:
        container_name: rainloop
        image: florentindubois/rainloop:latest
        restart: always

        volumes:
            - /srv/rainloop/data:/var/www/html/data

        expose:
            - "80"

    caddy:
        container_name: caddy
        image: florentindubois/caddy:latest
        restart: always

        volumes:
            - /srv/caddy:/root/.caddy
            - /srv:/srv/files

        links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - rainloop
            - kraken

        depends_on:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - kraken

        ports:
            - "80:80"
            - "443:443"
