version: '2'

services:
    portfolio:
        container_name: 'portfolio'
        image: portfolio

        expose:
            - "80"

    mariadb:
        container_name: mariadb
        image: mariadb:latest

        environment:
            - MYSQL_ROOT_PASSWORD=<password>

        ports:
            - "3305:3306"

        expose:
            - "3306"

        volumes:
            - /srv/mariadb:/var/lib/mysql

    owncloud:
        container_name: owncloud
        image: owncloud:latest

        expose:
            - "80"

        volumes:
            - /srv/owncloud:/var/www/html

        links:
            - mariadb

        depends_on:
            - mariadb

    deluge:
        container_name: deluge
        image: linuxserver/deluge

        environment:
            - PUID=0
            - PGID=0

        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "8112"
            - "58846"

        ports:
            - "7000-7009:7000-7009"

    sickrage:
        container_name: sickrage
        image: binhex/arch-sickrage

        expose:
            - "8081"

        volumes:
            - /srv/sickrage/media:/media
            - /srv/sickrage/data:/data
            - /srv/sickrage/config:/config
            - /etc/localtime:/etc/localtime:ro

        environment:
            - PUID=0
            - GUID=0

        links:
            - deluge

        depends_on:
            - deluge


    couchpotato:
        container_name: couchpotato
        image: linuxserver/couchpotato

        environment:
            - PGID=0
            - PUID=0

        volumes:
            - /srv/couchpotato/config:/config
            - /srv/couchpotato/downloads:/downloads
            - /srv/couchpotato/movies:/movies
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "5050"

        links:
            - deluge

        depends_on:
            - deluge

    rainloop:
        container_name: rainloop
        image: florentindubois/infrastructure:rainloop

        volumes:
            - /srv/rainloop/data:/var/www/html/data

        expose:
            - "80"

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin

        expose:
            - "80"

        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - PMA_ABSOLUTE_URI=data.florentin-dubois.fr

        links:
            - mariadb

        depends_on:
            - mariadb

    store:
        container_name: store
        image: store

        volumes:
            - /srv/h1z1-store:/var/www/html

        expose:
            - "80"

        links:
            - mariadb

        depends_on:
            - mariadb

    steambot:
        container_name: steambot
        image: steambot

        expose:
            - "80"

        depends_on:
            - store

    caddy:
        container_name: caddy
        image: florentindubois/infrastructure:caddy

        links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - rainloop
            - phpmyadmin
            - steambot

        volumes:
            - /srv/caddy:/root/.caddy

        depends_on:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - phpmyadmin
            - steambot

        ports:
            - "80:80"
            - "443:443"
