version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always

    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

    volumes:
      - /srv/postgres:/var/lib/postgresql/data

    expose:
      - '5432'

  owncloud:
    container_name: owncloud
    image: owncloud:latest
    restart: always

    volumes:
      - /srv/owncloud/config:/var/www/html/config
      - /srv/owncloud/data:/var/www/html/data

    links:
      - postgres:postgres

    depends_on:
      - postgres

    expose:
      - '80'

  ghost:
    build: ./ghost
    container_name: ghost
    image: florentindubois/infrastructure:ghost
    restart: always

    environment:
      - NODE_ENV=production

    expose:
      - '2368'

    links:
      - postgres:postgres

    depends_on:
      - postgres

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always

    environment:
        - PUID=0
        - PGID=0

    volumes:
        - /srv/deluge/downloads:/downloads
        - /srv/deluge/config:/config
        - /etc/localtime:/etc/localtime:ro

    expose:
        - "8112"
        - "58846"

    ports:
        - "7000-7009:7000-7009"

  sickrage:
    container_name: sickrage
    image: linuxserver/sickrage:latest
    restart: always

    expose:
        - "8081"

    volumes:
        - /srv/sickrage/media:/tv
        - /srv/sickrage/data:/downloads
        - /srv/sickrage/config:/config
        - /etc/localtime:/etc/localtime:ro

    environment:
        - TZ=Europe/Paris
        - PUID=0
        - GUID=0

    links:
        - deluge

    depends_on:
        - deluge

  warp10:
    container_name: warp10
    image: warp10io/warp10:1.0.7
    restart: always
    stdin_open: true

    volumes:
      - /srv/warp10:/data

    expose:
      - "8080"
      - "8081"

  noderig:
    build: ./noderig
    container_name: noderig
    image: runabove/noderig:latest
    restart: always
    network_mode: host

    volumes:
      - /etc/localtime:/etc/localtime:ro

    port:
      - "9100"

  beamium:
    build: ./beamium
    container_name: beamium
    image: runabove/beamium:latest
    restart: always
    network_mode: host

    volumes:
      - /etc/localtime:/etc/localtime:ro

    depends_on:
      - noderig
      - warp10

  caddy:
    build: ./caddy
    container_name: caddy
    image: florentindubois/infrastructure:caddy
    restart: always

    volumes:
      - /srv/caddy:/root/.caddy

    ports:
      - '80:80'
      - '443:443'

    links:
      - owncloud
      - ghost
      - deluge
      - sickrage
      - warp10

    depends_on:
      - owncloud
      - ghost
      - deluge
      - sickrage
      - warp10
