version: '2'

services:
    portfolio:
        container_name: 'portfolio'
        image: florentindubois/infrastructure:portfolio

        environment:
            - HOSTNAME=florentin-dubois.fr
            - CONTACT_EMAIL=dubois.florentin@live.fr
            - GITHUB_USERNAME=FlorentinDUBOIS
            - GITHUB_PASSWORD=
            - TWITTER_CONSUMER_KEY=
            - TWITTER_CONSUMER_SECRET=
            - TWITTER_ACCESS_TOKEN_KEY=
            - TWITTER_ACCESS_TOKEN_SECRET=
            - TWITTER_USERNAME=FlorentinDUBOIS
            - NODE_ENV=production

        expose:
            - "80"

    mariadb:
        container_name: mariadb
        image: mariadb:latest

        environment:
            - MYSQL_ROOT_PASSWORD=

        ports:
            - "3305:3306"

        expose:
            - "3306"

        volumes:
            - /srv/mariadb:/var/lib/mysql

    mongodb:
        container_name: mongodb
        image: mongo:latest

        expose:
            - "27017"

    kraken:
        container_name: kraken
        image: florentindubois/infrastructure:kraken

        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
            - MONGODB_BASE=kraken
            - NODE_ENV=production

        volumes:
            - /srv:/usr/src/app/mount:rw

        expose:
            - "80"

        links:
            - mongodb

        depends_on:
            - mongodb

    owncloud:
        container_name: owncloud
        image: owncloud:latest

        expose:
            - "80"

        volumes:
            - /srv/owncloud:/var/www/html

        links:
            - mariadb

        depends_on:
            - mariadb

    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest

        environment:
            - PUID=0
            - PGID=0

        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "8112"
            - "58846"

        ports:
            - "7000-7009:7000-7009"

    sickrage:
        container_name: sickrage
        image: binhex/arch-sickrage:latest

        expose:
            - "8081"

        volumes:
            - /srv/sickrage/media:/media
            - /srv/sickrage/data:/data
            - /srv/sickrage/config:/config
            - /etc/localtime:/etc/localtime:ro

        environment:
            - PUID=0
            - GUID=0

        links:
            - deluge

        depends_on:
            - deluge

    couchpotato:
        container_name: couchpotato
        image: linuxserver/couchpotato:latest

        environment:
            - PGID=0
            - PUID=0

        volumes:
            - /srv/couchpotato/config:/config
            - /srv/couchpotato/downloads:/downloads
            - /srv/couchpotato/movies:/movies
            - /etc/localtime:/etc/localtime:ro

        expose:
            - "5050"

        links:
            - deluge

        depends_on:
            - deluge

    rainloop:
        container_name: rainloop
        image: florentindubois/infrastructure:rainloop

        volumes:
            - /srv/rainloop/data:/var/www/html/data

        expose:
            - "80"

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin

        expose:
            - "80"

        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - PMA_ABSOLUTE_URI=data.florentin-dubois.fr

        links:
            - mariadb

        depends_on:
            - mariadb

    caddy:
        container_name: caddy
        image: florentindubois/infrastructure:caddy

        volumes:
            - /srv/caddy:/root/.caddy

        links:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - rainloop
            - phpmyadmin
            - kraken

        depends_on:
            - owncloud
            - portfolio
            - sickrage
            - couchpotato
            - deluge
            - phpmyadmin
            - kraken

        ports:
            - "80:80"
            - "443:443"
