version: '2'

services:
    h5ai:
        container_name: h5ai
        image: clue/h5ai

        volumes:
            - /srv/deluge/downloads:/var/www/deluge
            - /srv/sickrage/downloads:/var/www/sickrage
            - /srv/couchpotato/downloads:/var/www/couchpotato

        expose:
            - "80"
