version: '2'

services:
    owncloud:
        container_name: owncloud
        image: owncloud:latest

        expose:
            - "80"

        external_links:
            - mariadb

        volumes:
            - /srv/owncloud:/var/www/html
