version: '2'

services:
    rainloop:
        container_name: rainloop
        image: florentindubois/infrastructure:rainloop

        volumes:
            - /srv/rainloop/data:/var/www/html/data

        expose:
            - "80"
