sources:
  noderig:
    url: http://noderig:9100/metrics
    period: 1000
    format: sensision

sinks:
  warp10:
    url: http://warp10:8080/api/v0/update
    token:

parameters:
  log-file: /var/log/beamium.log
  log-level: 6

labels:
  host: dubois.ovh
