sources:
  noderig:
    url: http://noderig.dubois.ovh:9100/metrics
    period: 10000
    format: sensision

sinks:
  warp10:
    url: https://warp10.dubois.ovh/api/v0/update
    token:

parameters:
  log-file: /var/log/beamium.log
  log-level: 6

labels:
  host: dubois.ovh
